### ISSUE TITLE
Decoding on an Arduino

### ISSUE THREAD

**Issue by WyseNynja** [thesolarnomad/lora-serialization#16]
The serialization code looks perfect my project since it easily supports lat/long, but I want to deserialize on another Arduino. What do you recommend? Do you think its worth writing deserialization code in C, or should I use another library (https://github.com/francc/tinypacks/blob/master/README-TinyPacks.md maybe)?

**Comment by joscha** [comment]
Hey,

Happy to accept a PR that adds decoding for the Arduino side - but maybe have a look at https://github.com/thesolarnomad/ttn-proto-utils/blob/master/example/arduino/src/main.cpp - it uses protobuf to do the same thing and takes quite a bit of work out of your hands with marginally more bytes (and more flexibility). I haven't used tinypack before, bit that looks interesting as well.

**Comment by WyseNynja** [comment]
I'm going to use tinypb/protobuf. Thanks.
