### ISSUE TITLE
Boolean Datatype

### ISSUE THREAD

**Issue by Drasek** [thesolarnomad/lora-serialization#3]
Hello,

i really like this library and would love it another datatype: Boolean

It would be useful for stuff like "Battery Low: false/true" / "Something: on/off" / "Parking lot: occupied/free" and you could en/decode 8 Boolean datasets into 1 Byte.

```
message
    .addBoolean(true/false);
```

At the moment i have to use the uint8 datatype and do the bitshifting "by hand", it would be great to have this inside the library. Thank you very much!

**Comment by joscha** [comment]
sounds good to me - it could be a Bitmap type allowing for up to 8 booleans

**Comment by joscha** [comment]
Just implemented in `2.3.0`
