### ISSUE TITLE
Is this library still active and relevant?

### ISSUE THREAD

**Issue by hpssjellis** [thesolarnomad/lora-serialization#43]
@joscha **Is this library still active and relevant?**

Hi Joscha. Great library. I noticed that not much has happened on this repo for a few years, is that because it was just so well written it doesn't need any improvements or has it faded from use?

I am trying to understand serialization and wanting to write a tutorial to use encoding and decoding on the [Helium Network](https://www.helium.com/) . This repo seems the best that I have found so far, easy enough to understand and looks useful.  Any opinions?

**Comment by joscha** [comment]
@hpssjellis it's true there is not much momentum on the code itself, however I believe it's still being used in various places. You can see so by looking at the network graph and mentions of it in presentations, etc.
Whether it is the best, I have no idea and it'd be quite presuming on my behalf to make that claim. I do think the data type set is fairly complete, e.g. most standard sensor data out there can be sent with it out of the box and for more elaborate messages my assumption is that people use something more custom like protobuf. I would.

**Comment by hpssjellis** [comment]
@joscha Thanks so much for the reply. I might use your library as it is so easy to understand, however Protobuf.js looks amazing for the javascript side, wondering about the arduino implimentation. Found  https://github.com/eric-wieser/nanopb-arduino and will have to research it a bit.

I will close this issue.

**Comment by joscha** [comment]
Look at the other projects in this org, IIRC correctly one of them uses nano for the Arduino side. It worked like a charm, the only overhead you have is the padding.
