### ISSUE TITLE
4-byte Float Functions not provided in archive visible to Arduino Library Manager

### ISSUE THREAD

**Issue by matthias-bs** [thesolarnomad/lora-serialization#45]
If you want to use the functions writeRawFloat()/addRawFloat(), you must install from the head of the repository, i.e. neither use the Arduino Library Manager nor install the library from the v3.0.1 archive.

**Comment by joscha** [comment]
we can produce a new tag for HEAD - shall we get https://github.com/thesolarnomad/lora-serialization/pull/44 in first?

**Comment by matthias-bs** [comment]
Yes, it would be great to pull in [#44](/thesolarnomad/lora-serialization/pull/44) first.

**Comment by joscha** [comment]
Done. If you update the libraries I'll merge and create a new matching tag!

**Comment by matthias-bs** [comment]
Sorry, what do you mean by "if you update the libraries"?

**Comment by joscha** [comment]
The properties file will need a new minor version, won't it?

**Comment by matthias-bs** [comment]
Thank you for the update v3.1.0!
