### ISSUE TITLE
Missing LoraEncoder::getLength()

### ISSUE THREAD

**Issue by matthias-bs** [thesolarnomad/lora-serialization#50]
I am using LoraEncoder instead of LoraMessage, because a statically allocated buffer is perfectly fine for me.
Having a getLength() method would be greatly appreciated!

In my application, the data written to the buffer is configuration-dependent and I would like to avoid counting bytes in a second place.

**Comment by joscha** [comment]
I don't see why we can't have a method like that, do you want to open a pull request?

**Comment by matthias-bs** [comment]
Sure! Which approach would you prefer: keeping a variable `size` separately from the buffer or use a variable `offset` which is also used as follows:
```
void LoraEncoder::writeUint32(uint32_t i) {
    _intToBytes(_buffer+_offset, i, 4);
    _offset += 4;
}
```
I would prefer the latter.

**Comment by matthias-bs** [comment]
Thanks for the ultra quick reply!

**Comment by joscha** [comment]
I think the offset approach is a tad nicer, as the variable is actually used in all cases instead of carrying it along only for this case?

**Comment by matthias-bs** [comment]
Thank you very much for accepting the PR. Are you planning a new release soon?

**Comment by joscha** [comment]
Created 3.2.0 just now.

**Comment by matthias-bs** [comment]
Yes, but you did not update library.properties... ;-)

**Comment by joscha** [comment]
3.2.1

**Comment by matthias-bs** [comment]
Thanks a lot!
