### ISSUE TITLE
TypeError: Object has no member 'slice' at decodeUplink

### ISSUE THREAD

**Issue by shypard** [thesolarnomad/lora-serialization#52]
Hi!

First off, thanks for the Library, works great on Arduino / ESP Side. However I have still troubles decoding the data on the TTN side.
For the uplink formatter I have got the example code as such:
```javascript
function decodeUplink(bytes) {
	data = {};
	x = 0  // starting point
	data.fPort = uint8(bytes.slice(x, x + 1))
	return data
}

/* contents from src/decoder.js */
var bytesToInt = function(bytes) {
  var i = 0;
  for (var x = 0; x < bytes.length; x++) {
    i |= +(bytes[x] << (x * 8));
  }
  return i;
};
...
```

However upon testing I am receiving the above error: ``TypeError: Object has no member 'slice' at decodeUplink (<eval>:5:32(15))``
Does the ``bytes`` object need to be converted first, in order to use ``slice()`` or should I use it differently? 

Thanks & BR :)

**Comment by shypard** [comment]
Many thanks @joscha for the (indirect) hint, I found the error!
Turned out the ``bytes`` parameter was a dictionary, containing another key called ``bytes``. Running the following snippet:

```javascript
function decodeUplink(bytes) {
  throw new Error(JSON.stringify(bytes))
}
```
shows the passed ``bytes`` object: 
```javascript
{
  "bytes": [1, 2, 3],
  "fPort":10
}
```
Now we can convert them using 
```javascript
data.fPort = uint8(bytes.bytes.slice(x, x + 1));
```

BR, Christian :-)

**Comment by joscha** [comment]
I see, great! Did you copy that sample from somewhere in the docs? If yes, would you mind opening a PR to fix it, please?

**Comment by shypard** [comment]
No, the ``bytes`` data sample was from one of my tests. I just used the converter snippets from the [README.md](https://github.com/thesolarnomad/lora-serialization/blob/master/README.md), like: 
```javascript 
uint8(bytes.slice(x, x + 1)) // 10
```

I can however create a PR to replace the ``bytes`` with ``bytes.bytes`` or probably more understandable ``payload.bytes``, if you want.

**Comment by joscha** [comment]
Yes please!
