### ISSUE TITLE
library.properties not up-to-date

### ISSUE THREAD

**Issue by matthias-bs** [thesolarnomad/lora-serialization#57]
Hi,
There is a new release v3.3.0, but the version in library.properties is still 3.2.1.
Cheers,
Matthias

**Comment by joscha** [comment]
fixed via 059847ef9bca44f5bd9723020b5099f9c16df8a6 and a `v3.3.1` tag

**Comment by joscha** [comment]
(didn't create the change for 3.3.0 and move the tag)

**Comment by matthias-bs** [comment]
Thanks a lot!
