### ISSUE TITLE
sign of temperature values ignored

### ISSUE THREAD

**Issue by noerw** [thesolarnomad/lora-serialization#9]
it's impossible to decode negative temperature values; the positive value is always returned.
don't know if its an error in the decode or encode function, or both. see this code:

```js
const ls = require('lora-serialization'),
  enc = ls.encoder, dec = ls.decoder;

const buf = enc.encode([-25.3], [enc.temperature]);

// { temperature: 25.3 }
console.log(dec.decode(buf, [dec.temperature], ['temperature']));
```

**Comment by joscha** [comment]
Hi, thanks for the report. I can confirm temperatures between -81 and 0 and temperatures greater 82 seem to be affected. Haven't looked into the exact cause, yet, happy to merge any PR.

**Comment by noerw** [comment]
thanks for the quick fix! :+1:
